type scoredChoiceT = { choice: string; score: number };

type questionT = { question: string; choices: scoredChoiceT[] }[];

export const questions: questionT = [
  {
    question: 'Is your industry likely to grow in the next 5 years?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question:
      'Does the general public consume the products/services you are providing?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Do your products/services have Unique Selling Propositions?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Are the products/services offered trending now?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Is it easy for your target audience to convert to your brand?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Is your target audience active on Social Media?',
    choices: [
      { choice: 'Yes', score: 3 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Is your brand distinctive among your competition?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Are your competitors actively marketing?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Did you increase your online presence due to the pandemic?',
    choices: [
      { choice: 'Yes', score: 2 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Are your competitors generating online sales?',
    choices: [
      { choice: 'Yes', score: 3 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Is brand marketing important to your business?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Have you had a successful marketing promotion previously?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Does your business need new customers to stay profitable?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
  {
    question: 'Is your business losing existing/loyal customers?',
    choices: [
      { choice: 'Yes', score: 0 },
      { choice: 'No', score: 2 },
    ],
  },
  {
    question: 'Is your business ready to handle a sudden increase of sales?',
    choices: [
      { choice: 'Yes', score: 5 },
      { choice: 'No', score: 0 },
    ],
  },
];

export const results = [
  'Your business currently needs to strengthen its foundations. It is advisable for you to focus more on product positioning, branding and business operations at this time. As vital as marketing is to a business, it is equally important to focus on business strategy and brand communications.\n\nContact us for a free consultation on brand strategies for optimal results.\n\nIf you found this quiz beneficial, please help us to like and share it.\nThank you!',
  'Your business is ready for growth, thus it is a good practice for you to take 5% of the total revenue generated by your business and invest it on marketing. These include sales promotions, brand marketing and advertising campaigns.\n\nContact us for a free consultation on how to allocate your marketing budget for optimal results.\n\nIf you found this quiz beneficial, please help us to like and share it.\n\nThank you!',
  'Your business is poised for a major sales expansion. It is expedient for your business to take at least 10 to 15% out from the total revenue generated and invest it on marketing your business. These could be a combination of sales promotions, brand marketing and advertising campaigns.\n\nContact us for a free consultation on how to combine various marketing strategies for maximum results.\n\nIf you found this quiz beneficial, please help us to like and share it.\n\nThank you!',
];
